//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public int ID { get; set; }
        public int Team1ID { get; set; }
        public int Team2ID { get; set; }
        public int TournamentID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
