//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.TeamPlayers = new HashSet<TeamPlayer>();
        }
    
        public int PId { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Role { get; set; }
        public string BattingStyle { get; set; }
        public string BowlingStyle { get; set; }
    
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
        public virtual ICollection<TeamPlayer> TeamPlayers { get; set; }
    }
}
